### ISSUE TITLE
Piwik Tracking - missing slashes in piwik_url

### ISSUE THREAD

**Issue by shwebstart** [zenphoto/Unsupported#6]
Piwik URL is not set correctly, missing double slashes in URL

Source-Code: var u=(("https:" == document.location.protocol) ? "https" : "http") + "<?php echo $piwik_url ?>/";
Fix: var u=(("https:" == document.location.protocol) ? "https://" : "http://") + "<?php echo $piwik_url ?>/";

**Comment by acrylian** [comment]
Thanks! You could also have provided a pull request with both fixes.
