### ISSUE TITLE
index link to zpmasonry theme

### ISSUE THREAD

**Issue by eliz82** [zenphoto/Unsupported#7]
there is a problem with zpmasonry theme on zenphoto v1.4.12.
"Gallery Index" is link to "index.php?p=none" and when clicking it gives an error "Sorry, the page you are requesting cannot be found."

**Comment by fretzl** [comment]
In themeoptions.php change this line
`setThemeOption('custom_index_page','none',null,'zpmasonry');`
to
`setThemeOption('custom_index_page','',null,'zpmasonry');`

You'll have to click the "Revert to default" button (bottom of the theme options page) for it to take effect or run setup.
